### ISSUE TITLE
[BUG] Cannot create job via API

### ISSUE THREAD

**Issue by zethis** [shieldproject/shield#566]
**Describe the bug**
When i'm trying to create a job with the API i get this error:

```bash
http: panic serving 127.0.0.1:51632: runtime error: invalid memory address or nil pointer dereference
goroutine 131713 [running]:
net/http.(*conn).serve.func1(0xc420170820)
	/goroot/src/net/http/server.go:1697 +0xd0
panic(0x9e9a80, 0xf4ff50)
	/goroot/src/runtime/panic.go:491 +0x283
github.com/starkandwayne/shield/db.(*DB).CreateJob(0xc4200585c0, 0x0, 0x7, 0x0, 0x0)
	/tmp/build/01f561ac/gopath/src/github.com/starkandwayne/shield/db/jobs.go:256 +0x3b9
github.com/starkandwayne/shield/core.(*Core).v2API.func63(0xc42008dc20)
	/tmp/build/01f561ac/gopath/src/github.com/starkandwayne/shield/core/api_v2.go:2638 +0x42d
github.com/starkandwayne/shield/route.(*Router).ServeHTTP(0xc420111040, 0xf677c0, 0xc4201c8b60, 0xc420746f00)
	/tmp/build/01f561ac/gopath/src/github.com/starkandwayne/shield/route/route.go:36 +0x23c
net/http.(*ServeMux).ServeHTTP(0xc420085950, 0xf677c0, 0xc4201c8b60, 0xc420746f00)
	/goroot/src/net/http/server.go:2254 +0x130
net/http.serverHandler.ServeHTTP(0xc420099040, 0xf677c0, 0xc4201c8b60, 0xc420746f00)
	/goroot/src/net/http/server.go:2619 +0xb4
net/http.(*conn).serve(0xc420170820, 0xf67f40, 0xc4207a2640)
	/goroot/src/net/http/server.go:1801 +0x71d
created by net/http.(*Server).Serve
	/goroot/src/net/http/server.go:2720 +0x288
```

**To Reproduce**
1. Go to your terminal
2. Create a target, store, policy.
3. Run this curl: 
```bash
curl -k -H 'Accept: application/json' \
     -H 'X-Shield-Session: fbaed999-c4fd-403b-abc1-63426aceec9c' \
     -H 'Content-Type: application/json' \
     -X POST http://localhost:8080/v2/tenants/4f5de4f6-80c6-4d2d-8d30-4ca120774ea6/jobs \
     --data-binary '
{
  "name"        : "my-app",
  "summary"     : "A longer description...",
  "schedule"    : "daily 4am",
  "compression" : "bzip2",
  "paused"      : false,
  "store"       : "uuid-of-the-store",
  "target"      : "uuid-of-the-target",
  "policy"      : "uuid-of-the-policy",
  "retain"      : "7d"
}'
```
4. See error in the nginx logs

**Expected behavior**
Job created with success

**SHIELD versions (please complete the following information):**
 - SHIELD Core: 8.2.1
 - SHIELD CLI: shield v8.2.1

**Browser version(s) (please complete if reporting a web UI bug):**
 - OS: Ubuntu 18.04
 - Browser: Firefox 
 - Version: 67.0.4

**Comment by zethis** [comment]
Ok, i find something.
I got this error because the uuid of the store is not good, in my case the store was not created.

**Comment by jhunt** [comment]
Fun part is the API allows the record, but fails on the retrieve, leaving stuff in the database:

```
sqlite> select * from jobs WHERE store_uuid = 'uuid-of-the-store';
f0f830b3-dc38-4384-8d77-559845c3bf91|uuid-of-the-target|uuid-of-the-store|1357aa95-817f-42fc-92a8-e3c0cb7c455b|my-app|A longer description...|daily 4am|7|7|0|50|0|0
3e44ad9e-29e2-4966-a124-85a0b5d173cb|uuid-of-the-target|uuid-of-the-store|1357aa95-817f-42fc-92a8-e3c0cb7c455b|my-app|A longer description...|daily 4am|7|7|0|50|0|0
8a9c89b9-fea6-45ef-ad95-475ae2045b9b|uuid-of-the-target|uuid-of-the-store|1357aa95-817f-42fc-92a8-e3c0cb7c455b|my-app|A longer description...|daily 4am|7|7|0|50|0|0
```

This probable needs an overhaul of validation in the API front-end, a way of atomically locking multi-statement updates, and a fixup to clear out orphaned records.

**Comment by jhunt** [comment]
Putting the data validation in the `db` layer makes the most sense.  Here's the response we now get to the above query:

```
Response:
HTTP/1.1 500 Internal Server Error
Connection: close
Content-Length: 153
Content-Type: application/json
Date: Fri, 23 Aug 2019 14:36:37 GMT

{"diagnostic":"server-side error: unable to create job against store [uuid-of-the-store]: no such store in database","error":"Unable to create new job"}

---------------------------
{
 "diagnostic": "server-side error: unable to create job against store [uuid-of-the-store]: no such store in database",
 "error": "Unable to create new job"
}
```

I will try to get more relationship validations into the db layer for 8.5
